---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
```


# Load data

Fishing data

```{r}
fish<-read.csv(here("output_data/Fishing_data_clean.csv"))
```

Management data

```{r}
me<-read.csv(here("output_data/Management_data_clean.csv"))
```

Join data

```{r}
fish_me<-full_join(fish, me, by = c("Fished_ISO3" = "Export_ISO3"))   %>% 
  mutate(Fishing_ISO3 = as.character(Fishing_ISO3),
         Fished_ISO3 = as.character(Fished_ISO3)) %>% 
  filter(Year>=1976,
         Year <= 2015) %>% 
  dplyr::select(-X.x, -X.y)

test<-fish_me %>% 
  filter(is.na(ME_score) == T)

# These countries do not have an ME score
unique(test$Export_ISO3)
```
# Total fishing

```{r}
fishing<-fish_me %>% 
  group_by(Fishing_ISO3, Year) %>% 
  summarise(Total_fished = sum(Total_fished, na.rm = T))
```

# Displaced (imported) by country

EEZ and High Seas

```{r}
fish_displaced<- fish_me %>% 
  filter(!Fishing_ISO3 == Fished_ISO3) %>% 
  group_by(Fishing_ISO3, Fished_ISO3, Year) %>% 
  summarise(disp_fished = sum(Total_fished, na.rm = T)) 

all_fish_displaced<-fish_displaced %>% 
  group_by(Fishing_ISO3, Year) %>% 
  summarise(disp_fished = sum(disp_fished, na.rm = T))


test<-all_fish_displaced %>% 
  filter(Fishing_ISO3 == "AGO",
         Year %in% c(2011,2012,2013,2014,2015))
```



# Unequal Import Displacement

Displacement (imports) from countries with lower management

```{r}
unequal<-fish_me %>% 
  filter(!Fishing_ISO3 == Fished_ISO3) %>% 
  full_join(., me, by = c("Fishing_ISO3" = "Export_ISO3")) %>% 
  rename(Fished_ME = ME_score.x,
         Fishing_ME = ME_score.y) %>% 
  mutate(Fished_ME = ifelse(Fished_ISO3 == "HighSeas", 49,Fished_ME))

sub_unequal<-unequal %>% 
  filter(Fished_ME < Fishing_ME)

unequal_fish<- sub_unequal %>% 
  group_by(Fishing_ISO3, Year) %>% 
  summarise(unequal_fish = sum(Total_fished, na.rm = T))
  
```

High Seas only

```{r}
unequal_hs<-fish_me %>% 
  filter(!Fishing_ISO3 == Fished_ISO3,
         Fished_ISO3 == "HighSeas") %>% 
  full_join(., me, by = c("Fishing_ISO3" = "Export_ISO3")) %>% 
  rename(Fished_ME = ME_score.x,
         Fishing_ME = ME_score.y) %>% 
  mutate(Fished_ME = ifelse(Fished_ISO3 == "HighSeas", 49,Fished_ME))

sub_unequal_hs<-unequal_hs %>% 
  filter(Fished_ME < Fishing_ME)

unequal_fish_hs<- sub_unequal_hs %>% 
  group_by(Fishing_ISO3, Year) %>% 
  summarise(unequal_fish_hs = sum(Total_fished, na.rm = T))
  
```
# Unequal fishing in each countries waters

```{r}
unequal_waters<-sub_unequal %>% 
  group_by(Fished_ISO3, Year) %>% 
  summarise(unequal_fishing_in_waters = sum(Total_fished, na.rm = T))
```

# Final table
Join 

```{r}
fish_results<-full_join(fishing, all_fish_displaced) %>% 
  full_join(., unequal_fish) %>% 
  full_join(., unequal_fish_hs) %>% 
  full_join(., unequal_waters, by = c("Fishing_ISO3" = "Fished_ISO3", "Year")) %>% 
  mutate(unequal_fish_eez = unequal_fish - unequal_fish_hs,
        prop_disp = disp_fished/Total_fished,
        prop_unequal_disp = unequal_fish/disp_fished)
```



```{r}
write.csv(fish_results, here("output_data/Fish_displacement.csv"))
```

